{% set name = "astrometry" %}
{% set version = "0.93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dstndstn/astrometry.net/archive/{{ version }}.zip
  sha256: cfe7cdd59886b3f09bb7a93b6094669e1785761ea11df02bbc03810c2e10242c

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - swig
    - make
    - pkg-config
    - python
  host:
    - xorg-libx11
    - xorg-libxau
    - xorg-libxext
    - xorg-libxrender
    - xorg-xproto
    - numpy
    - zlib
    - libjpeg-turbo
    - netpbm
    - libpng
    - cfitsio
    - astropy
    - bzip2
    - cairo
    - gsl
    - wcslib
    - python
  run:
    - zlib
    - libjpeg-turbo
    - netpbm
    - libpng
    - cfitsio
    - astropy
    - {{ pin_compatible('numpy') }}
    - bzip2
    - cairo
    - gsl
    - wcslib
    - python

test:
  commands:
    - solve-field -h

about:
  home: http://astrometry.net/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Automatic recognition of astronomical images; or standards-compliant astrometric metadata from data.
  description: |
    If you have astronomical imaging of the sky with celestial coordinates you do not know—or do not
    trust—then Astrometry.net is for you. Input an image and we'll give you back astrometric
    calibration meta-data, plus lists of known objects falling inside the field of view
  doc_url: http://astrometry.net/doc/readme.html
  dev_url: https://github.com/dstndstn/astrometry.net/

extra:
  recipe-maintainers:
    - juliotux
