{% set name = "astrometry" %}
{% set version = "0.79" %}

package:
  name: {{ name|lower}}
  version: {{ version }}

source:
  url: https://github.com/dstndstn/astrometry.net/archive/{{ version }}.zip
  sha256: d85673f4ac8a51740aa8d79d65b29b6db725a14995f8f59a912f1288e90198bb

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - swig
    - make
    - pkg-config
  host:
    - xorg-libx11
    - xorg-libxau
    - xorg-libxext
    - xorg-libxrender
    - xorg-xproto
    - numpy
    - zlib
    - jpeg
    - netpbm
    - libpng
    - cfitsio
    - astropy
    - bzip2
    - cairo
    - gsl
    - wcslib
  run:
    - zlib
    - jpeg
    - netpbm
    - libpng
    - cfitsio
    - astropy
    - {{ pin_compatible('numpy') }}
    - bzip2
    - cairo
    - gsl
    - wcslib

test:
  commands:
    - solve-field -h

about:
  home: http://astrometry.net/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Automatic recognition of astronomical images; or standards-compliant astrometric metadata from data.
  description: |
     If you have astronomical imaging of the sky with celestial coordinates you do not know—or do not
     trust—then Astrometry.net is for you. Input an image and we'll give you back astrometric
     calibration meta-data, plus lists of known objects falling inside the field of view
  doc_url: http://astrometry.net/doc/readme.html
  dev_url: https://github.com/dstndstn/astrometry.net/

extra:
  recipe-maintainers:
    - juliotux
