travis:
  secure:
    BINSTAR_TOKEN: h5yj/p9oKdje0WXSswuQbAJopJTUmPGvUOlXHTXMXi6d8voq8HHkHdnOuI/OLCvQMhWDWMvCm4D0GIm27wuKCgppKtMd9NNxh6uj9dBcpjhXR0Ul7o4Aw2esomIYwvLoBsY5335uW2kc8A5rO/2BK7e+SPodJs0OU7S6Fl2yFQemw3pk65ZMuD+Abhd0g2fwcRHv+N3LbFFpKpks+uwbYYfmbBjOoVbC3qjOOV/9P+Rl9MznxnGhxJJS6jbnxZePf2JuEi+ztf4I09Dh1ZLDFVkZHogU7eWYW3t+/EGS5e+XG/lR9bV2OZTl+aFIrq9/utuxADUlc+xviKwMD7/XvtTBN0rlplsrsIJWtyL1Y5OrxhvVxDTian/1moMpAzvONgA60wYhtZdCSsW/EDjz/M5ceLiqWZAVQpM6f4I2MN94NknVB/xzvCEQqTMSYrNbcfQNVrDYwOm10wwtTP/zZTdOLpNLD0lvbTAKrUJKuNZu9qEe8jdvEbJa7Oq55kpVY80i4Fw+hgWU92YccGhzEuvNgHdlf4whoxdsV+k14F7t4fE0M9GE5Vu95/gNcG7BPdsUBW9zbkLv3zq2e9Ab4miE6ZcTyiuqnFwH4eN57GOrnyr++e7NPREM9KTqfKiU0Q/zllIMJ+ES1CGiZWXFLMbWoIVDrf33tr4BmC1393o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
